services:
  preprocessing:
    build:
      context: ./plugins/cd4ml/data_processing
      dockerfile: Dockerfile
    volumes:
      - "./data:/data"
    command: ["python", "run_preprocessing.py"]

############### dummy service model_training for now ###############
  model_training:
    image: alpine
    command: ["echo", "model_training placeholder"]

################ save it for later ################
  # model_training:
  #   build:
  #     context: .
  #     dockerfile: ./cd4ml/model_training/Dockerfile
  #   volumes:
  #     - "./data:/data"
  #   depends_on:
  #     - preprocessing
  #   command: ["python", "run_training.py"]

############### dummy service model_validation for now ###############
  model_validation:
    image: alpine
    command: ["echo", "model_validation placeholder"]

################ save it for later ################
  # model_validation:
  #   build:
  #     context: .
  #     dockerfile: ./cd4ml/model_validation/Dockerfile
  #   volumes:
  #     - "./data:/data"
  #   depends_on:
  #     - model_training
  #   command: ["python", "run_validation.py"]

  inference:
    build:
      context: ./plugins/cd4ml/inference
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./data:/data"
      - "./models:/app/models"
    depends_on:
      - model_validation
    command: ["uvicorn", "infer:app", "--host", "0.0.0.0", "--port", "8000"]