services:
  dvc-sync:
    build:
      context: ./dockerfiles/dvc
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - dvc-cache:/workspace/.dvc/cache
    working_dir: /workspace
    environment:
  # Authentification
      - DAGSHUB_USER_TOKEN=${DAGSHUB_USER_TOKEN} 
      - DAGSHUB_REPO_OWNER=${DAGSHUB_REPO_OWNER}
      - DAGSHUB_REPO_NAME=${DAGSHUB_REPO_NAME}
    command: ["dvc", "pull", "--force"]
  auth_service:
    build:
      context: .
      dockerfile: dockerfiles/auth_service/Dockerfile
    env_file:
      - .env
    ports:
      - "8001:8001"
    command: ["uvicorn", "plugins.cd4ml.inference.auth_service:auth_app", "--host", "0.0.0.0", "--port", "8001"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8001/health"]
      interval: 30s
      timeout: 5s
      retries: 5

  predict_service:
    build:
      context: .
      dockerfile: dockerfiles/predict_service/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - "./shared_volume/data:/app/data"
      - "./shared_volume/models:/app/models"
      - dvc-cache:/workspace/.dvc/cache
    depends_on:
      auth_service:
        condition: service_healthy
      dvc-sync:
        condition: service_completed_successfully
    command: ["uvicorn", "plugins.cd4ml.inference.predict_service:predict_app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  dvc-cache:
    