services:

  drift_monitor:
    build:
      context: .
      dockerfile: dockerfiles/monitoring/Dockerfile
    container_name: drift_monitor_service
    restart: unless-stopped
    networks:
      - drift-net
    volumes:
      - ../shared_volume:/app/shared_volume    # DVC-Daten liegen unter /app/shared_volume
      - ../logs:/app/drift_monitor             # Reports landen immer in /app/drift_monitor
    depends_on:
      - pushgateway
    environment:
      - PUSHGATEWAY_URL=http://pushgateway:9091
      - PUSHGATEWAY_JOB=drift_monitor
    command: ["supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway_service
    ports:
      - "9091:9091"
    networks:
      - drift-net

  prometheus:
    image: prom/prometheus:v2.36.2
    container_name: prometheus_service
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - pushgateway
    networks:
      - drift-net

  grafana:
    image: grafana/grafana:9.0.0
    container_name: grafana_service
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=Passwort123!
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - drift-net

volumes:
  grafana_data:

networks:
  drift-net:
    driver: bridge
