services:
  dvc-sync:
    build:
      context: "./dockerfiles/dvc"
      dockerfile: "Dockerfile"
    working_dir: /app
    env_file:
      - ./.env
    volumes:
      - .:/app                      # gesamtes Repo inkl. .git und .dvc
      - dvc-cache:/app/.dvc/cache    # gemeinsamer DVC-Cache
      - ./shared_volume:/app/shared_volume
    command: ["dvc", "pull", "--force"]

  drift_monitor:
    build:
      context: .
      dockerfile: dockerfiles/monitoring/Dockerfile
    container_name: drift_monitor_service
    env_file:
      - ./.env
    volumes:
      - ./shared_volume:/app/shared_volume  # nur Daten & Metriken
      - dvc-cache:/app/.dvc/cache          # DVC-Cache vom dvc-sync
    environment:
      - PREDICT_URL=http://predict_service:8002/predict
      - VALIDATION_DATA=/app/shared_volume/data/validation/labels.npy
      - PUSHGATEWAY_URL=http://pushgateway:9091
      - BATCH_SIZE=100
      - INTERVAL_SEC=300
    depends_on:
      pushgateway:
        condition: service_started
      dvc-sync:
        condition: service_completed_successfully
    networks:
      - drift-net

  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway_service
    ports:
      - "9091:9091"
    networks:
      - drift-net

  prometheus:
    image: prom/prometheus:v2.36.2
    container_name: prometheus_service
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - pushgateway
    networks:
      - drift-net

  alertmanager:
    image: prom/alertmanager:v0.24.0
    container_name: alertmanager_service
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    depends_on:
      - prometheus
    networks:
      - drift-net

  grafana:
    image: grafana/grafana:9.0.0
    container_name: grafana_service
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=Passwort123!
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - drift-net

volumes:
  grafana_data:
  dvc-cache:

networks:
  drift-net:
    driver: bridge
