[project]
name = "rakuten project dvc-within-docker"
version = "0.1.0"
description = "Rakuten project orchestration with dvc within docker containers"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dvc[s3]>=3.59.1",
]