global:
  resolve_timeout: 5m

route:
  receiver: 'airflow_retrain'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: 'airflow_retrain'
    webhook_configs:
      - url: "http://airflow-webserver:8080/api/v1/dags/ml_pipeline_mixed_experiment_dvc/dagRuns"
        send_resolved: false
        http_config:
          basic_auth:
            username: _AIRFLOW_WWW_USER_USERNAME
            password: _AIRFLOW_WWW_USER_PASSWORD
        # Neccessary if you want to use the Airflow API with basic auth or session auth
        # json_content:
        #   conf: {}
