groups:
- name: startup-check
  rules:
  - alert: PredictServiceF1TooLow
    expr: prediction_f1_score < 0.65                                             
    labels:
      severity: critical
    annotations:
      summary: "F1-Score of predict_service is under 65 %"
      description: "Current F1-Score is {{ $value }} ."
