groups:
  - name: prediction-service-alerts
    folder: ML-Service-Alerts 
    rules:
      - alert: F1_Score_Too_Low_Prediction_Service
        expr: prediction_f1_score < (0.73*0.9)
        for: 5m
        labels:
          severity: warning
          service: predict_service
          threshold_value: "0.657"
        annotations:
          summary: "F1-Score of Prediction Service is below threshold"
          description: "F1-Score of Prediction Service is {{ $value }}. That is below the configured threshold of {{ .Labels.threshold_value }}."