global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'auth_service'
    static_configs:
      - targets: ['auth_service:8001']

  - job_name: 'predict_service'
    static_configs:
      - targets: ['predict_service:8002']

  - job_name: 'api_probe'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - 'http://predict_service:8002/health'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'
        
