# monitoring/prometheus/recording_rules.yml
# -------------------------
# Recording Rules (Best Practices)
# - Kurz & prägnant benennen: <scope>:<metric_name>:<aggregation>
# - Labels immer beibehalten oder gezielt entfernen
# - Gruppen nach Themenschwerpunkten (System, HTTP, Latency, Business)

groups:

  # 1. System-Level Metrics
  - name: system_metrics
    interval: 1m       # Häufigkeit, in der Rules berechnet werden
    rules:
      # CPU usage per job (5m average)
    - record: job:process_cpu_seconds_total:rate5m
      expr: rate(process_cpu_seconds_total[5m])
      labels:
        unit: "seconds"

      # Resident memory per job
    - record: job:memory_resident_bytes
      expr: process_resident_memory_bytes
      labels:
        unit: "bytes"

      # Open file descriptors per job
    - record: job:open_fds
      expr: process_open_fds


  # 2. HTTP Request Metrics
  - name: http_request_metrics
    interval: 1m
    rules:
      # Request rate per endpoint for auth & predict services
    - record: job:http_request_rate:1m
      expr: |
        sum by(job, endpoint) (
          rate({__name__=~".*_requests_total"}[1m])
        )
      labels:
        unit: "req/s"

      # Error rate (non-2xx) per job
    - record: job:http_error_rate:1m
      expr: |
        sum by(job) (
          rate({__name__=~".*_requests_total", status_code!~"2.."}[1m])
        )
      labels:
        unit: "err/s"


  # 3. Latency Metrics
  - name: request_latency_quantiles
    interval: 1m
    rules:
      # 95th percentile latency per endpoint
    - record: job:http_request_latency_95p
      expr: |
        histogram_quantile(
          0.95,
          sum by(job, endpoint, le) (
            rate({__name__=~".*_latency_seconds_bucket"}[5m])
          )
        )
      labels:
        unit: "seconds"

      # 50th percentile latency (median)
    - record: job:http_request_latency_50p
      expr: |
        histogram_quantile(
          0.50,
          sum by(job, endpoint, le) (
            rate({__name__=~".*_latency_seconds_bucket"}[5m])
          )
        )
      labels:
        unit: "seconds"


  # 4. Business/Custom Metrics
  - name: business_metrics
    interval: 5m
    rules:
      # Weighted F1 score gauge (persisted)
    - record: job:prediction_f1_score
      expr: prediction_f1_score
