jobs:
  compose-check:
    name: Lint & Build Docker Compose Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create empty .env
        run: touch .env

      - name: Check Docker Compose version
        run: docker compose version

      - name: Validate syntax in docker-compose.yml
        run: docker compose -f docker-compose.yml config

      - name: Quick-Build docker-compose.yml (no-cache)
        run: docker compose -f docker-compose.yml build --no-cache

      - name: Validate syntax in docker-compose.inference.yml
        run: docker compose -f docker-compose.inference.yml config

      - name: Quick-Build docker-compose.inference.yml (no-cache)
        run: docker compose -f docker-compose.inference.yml build --no-cache

  tests:
    name: Build Final Docker Compose Services (no run, no DVC/MLflow)
    runs-on: ubuntu-latest
    needs:
      - compose-check

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create empty .env
        run: touch .env

      - name: Patch Dockerfiles for Compose build
        run: |
          sed -i 's/^RUN .*dvc pull.*/# &/g' dockerfiles/tests/Dockerfile || true
          sed -i 's/^RUN .*dvc push.*/# &/g' dockerfiles/tests/Dockerfile || true
          sed -i 's/^RUN .*pytest.*/# &/g' dockerfiles/tests/Dockerfile || true
          sed -i 's/^RUN .*dvc push.*/# &/g' dockerfiles/model_validation/Dockerfile || true
          sed -i 's/^RUN cp -R shared_volume\/data/# &/g' dockerfiles/tests/Dockerfile || true
          sed -i 's/^RUN cp -R shared_volume\/models/# &/g' dockerfiles/tests/Dockerfile || true

      - name: Build services from docker-compose.yml (SKIP actual run)
        run: docker compose -f docker-compose.yml build

      - name: Build services from docker-compose.inference.yml (SKIP actual run)
        run: docker compose -f docker-compose.inference.yml build