# .github/workflows/docker-publish.yml
name: Build, Test & Push Docker Images

on:
  push:
    branches:
      - main
      - develop
      - dev_new-feature-githubactions

permissions:
  contents: read

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    # pro Service+Branch immer nur einen Lauf gleichzeitig
    concurrency:
      group: build-${{ matrix.service }}-${{ github.ref_name }}
      cancel-in-progress: true

    strategy:
      matrix:
        service: [auth_service, predict_service]

    env:
      # Docker-Hub-Credentials aus den Repository-Secrets
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN:    ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      # 1) Code auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Python auf dem Runner einrichten
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) Dependencies installieren (inkl. pytest)
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      # 4) Tests auf dem Runner ausführen
      - name: Run unit tests for ${{ matrix.service }}
        run: |
          pytest plugins/cd4ml/tests/${{ matrix.service }} -v -rA

      # 5) Login zu Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      # 6) QEMU + Buildx (optional, Multiplattform)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 7) Docker-Image bauen
      - name: Build ${{ matrix.service }}
        run: |
          docker build \
            -f dockerfiles/${{ matrix.service }}/Dockerfile \
            -t igurstein/rakuten_dev:${{ matrix.service }}-${{ github.ref_name }} \
            .

      # 8) Docker-Image pushen
      - name: Push ${{ matrix.service }} to Docker Hub
        run: |
          docker push igurstein/rakuten_dev:${{ matrix.service }}-${{ github.ref_name }}

      # 9) optional: latest-Tag auf main
      - name: Tag ${{ matrix.service }} as latest
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag \
            igurstein/rakuten_dev:${{ matrix.service }}-main \
            igurstein/rakuten_dev:${{ matrix.service }}-latest
          docker push igurstein/rakuten_dev:${{ matrix.service }}-latest