# .github/workflows/docker-publish.yml
name: Build, Test & Push Docker Images

on:
  push:
    branches:
      - main
      - develop
      - dev_new-feature-githubactions

permissions:
  contents: read

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    # Pro Service+Branch immer nur ein Lauf gleichzeitig
    concurrency:
      group: build-${{ matrix.service }}-${{ github.ref_name }}
      cancel-in-progress: true

    strategy:
      matrix:
        service: [auth_service, predict_service]

    env:
      # Damit Tests auch deine Module finden
      PYTHONPATH: ${{ github.workspace }}
      # Docker Hub Credentials
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN:    ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      # 1) Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Python auf Runner
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) Installiere alle Test-Dependencies aus deinem tests/requirements.txt
      - name: Install test dependencies
        run: |
          pip install -r dockerfiles/tests/requirements.txt

      # 4) Unit-Tests auf dem Runner
      - name: Run unit tests for ${{ matrix.service }}
        run: |
          pytest plugins/cd4ml/tests/${{ matrix.service }} -v -rA

      # 5) Login zu Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      # 6) Optional: QEMU + Buildx (für Multi-Architektur)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 7) Docker-Image bauen
      - name: Build ${{ matrix.service }}
        run: |
          docker build \
            -f dockerfiles/${{ matrix.service }}/Dockerfile \
            -t igurstein/rakuten_dev:${{ matrix.service }}-${{ github.ref_name }} \
            .

      # 8) Docker-Image pushen
      - name: Push ${{ matrix.service }} to Docker Hub
        run: |
          docker push igurstein/rakuten_dev:${{ matrix.service }}-${{ github.ref_name }}

      # 9) Auf main: Tag als latest
      - name: Tag ${{ matrix.service }} as latest
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag \
            igurstein/rakuten_dev:${{ matrix.service }}-main \
            igurstein/rakuten_dev:${{ matrix.service }}-latest
          docker push igurstein/rakuten_dev:${{ matrix.service }}-latest