name: CI & Docker-Publish

on:
  push:
    branches: [ main, develop, dev_new-feature-githubactions ]
  pull_request:
    branches: [ main, develop, dev_new-feature-githubactions ]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          # 1) Projekt-Abhängigkeiten (falls vorhanden)
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # 2) Test-Framework und HTTP-Client
          pip install pytest fastapi requests httpx PyJWT

      - name: Pull DVC-Daten (optional)
        env:
          DVC_TOKEN: ${{ secrets.DAGSHUB_USER_TOKEN }}
          DVC_OWNER: ${{ secrets.DAGSHUB_REPO_OWNER }}
          DVC_REPO: ${{ secrets.DAGSHUB_REPO_NAME }}
        run: |
          if [ -n "$DVC_TOKEN" ]; then
            pip install "dvc[datascience]"
            export DAGSHUB_USER_TOKEN=$DVC_TOKEN
            export DAGSHUB_REPO_OWNER=$DVC_OWNER
            export DAGSHUB_REPO_NAME=$DVC_REPO
            dvc pull --force
          else
            echo "No DVC token, skipping pull."
          fi

      - name: Run pytest
        run: pytest plugins/cd4ml/tests/test_predict_service.py -v -rA

  publish:
    name: Build & Push Docker Images
    needs: test
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    strategy:
      matrix:
        service: [ auth_service, predict_service ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build & push ${{ matrix.service }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: dockerfiles/${{ matrix.service }}/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
            ${{ env.DOCKERHUB_USERNAME }}/${{ matrix.service }}:${{ github.sha }}