name: CI & Docker-Publish

on:
  push:
    branches: [ main, develop, dev_new-feature-githubactions ]
  pull_request:
    branches: [ main, develop, dev_new-feature-githubactions ]


permissions:
  contents: read

jobs:
  e2e-test:
    name: Run tests via Docker Compose
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare .env and shared_volume
        run: |
          # Create empty .env so docker compose env_file nicht fehlt
          touch .env
          # Create dummy folders for shared_volume to satisfy Dockerfile cp-commands
          mkdir -p shared_volume/data shared_volume/models

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build all services
        run: docker compose build

      - name: Run tests container
        run: docker compose up --abort-on-container-exit --exit-code-from tests

      - name: Tear down
        if: always()
        run: docker compose down --volumes --remove-orphans

  detect-changes:
    name: Detect changed services
    needs: e2e-test
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.set-services.outputs.services }}
    steps:
      - name: Full checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine changed services
        id: set-services
        run: |
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "Changed files: $CHANGED"
          services=()
          if echo "$CHANGED" | grep -qE '^dockerfiles/auth_service/|^plugins/cd4ml/inference/auth_service'; then
            services+=('"auth_service"')
          fi
          if echo "$CHANGED" | grep -qE '^dockerfiles/predict_service/|^plugins/cd4ml/inference/predict_service'; then
            services+=('"predict_service"')
          fi
          if [ ${#services[@]} -eq 0 ]; then
            echo "services=[]" >> $GITHUB_OUTPUT
          else
            echo "services=[${services[*]}]" >> $GITHUB_OUTPUT
          fi

  publish:
    name: Build & Push Docker Images
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.services != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.services) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push ${{ matrix.service }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: dockerfiles/${{ matrix.service }}/Dockerfile
          push: true
          tags: |
            igurstein/rakuten_dev:${{ matrix.service }}-latest
            igurstein/rakuten_dev:${{ matrix.service }}-${{ github.sha }}