name: CI & Docker-Publish

on:
  push:
    branches: [ main, develop, dev_new-feature-githubactions ]
  pull_request:
    branches: [ main, develop, dev_new-feature-githubactions ]


permissions:
  contents: read

jobs:
  test:
    name: Run pytest
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create predict_api alias for tests
        run: |
          echo "from plugins.cd4ml.inference.predict_service import predict_app, SECRET_KEY, ALGORITHM" > predict_api.py

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          # Core-Abhängigkeiten, falls vorhanden
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Test-Framework und alle weiteren Pakete, die deine Tests brauchen
          pip install pytest fastapi requests httpx PyJWT joblib mlflow

      - name: Run pytest
        run: pytest -q

  detect-changes:
    name: Detect changed services
    runs-on: ubuntu-latest
    #needs: test
    outputs:
      services: ${{ steps.set-services.outputs.services }}
    steps:
      - name: Checkout full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine changed services
        id: set-services
        run: |
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "Changed files: $CHANGED"

          services=()
          if echo "$CHANGED" | grep -qE '^dockerfiles/auth_service/|^plugins/cd4ml/inference/auth_service'; then
            services+=('"auth_service"')
          fi
          if echo "$CHANGED" | grep -qE '^dockerfiles/predict_service/|^plugins/cd4ml/inference/predict_service'; then
            services+=('"predict_service"')
          fi

          if [ ${#services[@]} -eq 0 ]; then
            echo "services=[]" >> $GITHUB_OUTPUT
          else
            echo "services=[${services[*]}]" >> $GITHUB_OUTPUT
          fi

  build-and-push:
    name: Build & Push Docker Images
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.services != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.services) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push ${{ matrix.service }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: dockerfiles/${{ matrix.service }}/Dockerfile
          push: true
          tags: |
            igurstein/rakuten_dev:${{ matrix.service }}-latest
            igurstein/rakuten_dev:${{ matrix.service }}-${{ github.sha }}