# .github/workflows/docker-publish.yml
name: Build, Test & Push Docker Images

on:
  push:
    branches:
      - main
      - develop
      - dev_new-feature-githubactions

permissions:
  contents: read

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    # Verhindert parallel laufende Builds desselben Service+Branch
    concurrency:
      group: build-${{ matrix.service }}-${{ github.ref_name }}
      cancel-in-progress: true

    strategy:
      matrix:
        service: [auth_service, predict_service]

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN:    ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      # 1) Code auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Login zu Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      # 3) QEMU + Buildx (optional, falls Multiplattform nötig)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4) Image bauen
      - name: Build ${{ matrix.service }}
        run: |
          docker build \
            -f dockerfiles/${{ matrix.service }}/Dockerfile \
            -t igurstein/rakuten_dev:${{ matrix.service }}-${{ github.ref_name }} \
            .

      # 5) Unit-Tests im Container
      - name: Run unit tests for ${{ matrix.service }}
        run: |
          docker run --rm igurstein/rakuten_dev:${{ matrix.service }}-${{ github.ref_name }} \
            sh -c "pytest plugins/cd4ml/tests/${{ matrix.service }} -v -rA"

      # 6) Image pushen
      - name: Push ${{ matrix.service }} to Docker Hub
        run: |
          docker push igurstein/rakuten_dev:${{ matrix.service }}-${{ github.ref_name }}

      # 7) latest-Tag auf main
      - name: Tag ${{ matrix.service }} as latest
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag \
            igurstein/rakuten_dev:${{ matrix.service }}-main \
            igurstein/rakuten_dev:${{ matrix.service }}-latest
          docker push igurstein/rakuten_dev:${{ matrix.service }}-latest