name: "CI/CD: Test, Build & Push Docker Images"

# Ensure only one concurrent run per branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Trigger on pushes to main, develop, and our test branch
on:
  push:
    branches: [ main, develop, dev_new-feature-githubactions ]

env:
  IMAGE_NAME: igurstein/rakuten_dev    # your DockerHub repo
  TAG: ${{ github.sha }}               # immutable commit-specific tag

jobs:
  # 1) Run Python tests & DVC steps in a virtualenv
  test-venv:
    name: Run DVC sync & unit tests in virtualenv
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Create virtualenv & install deps
        run: |
          python -m venv .venv
          echo "Upgrading pip & setuptools"
          .venv/bin/pip install --upgrade pip setuptools

          echo "Installing project requirements"
          if [ -f requirements.txt ]; then
            .venv/bin/pip install -r requirements.txt
          else
            echo "No requirements.txt found."
          fi

          echo "Installing test-only dependencies"
          # include dvc[s3] so S3 remotes work
          .venv/bin/pip install pytest joblib fastapi httpx mlflow PyJWT "dvc[s3]"

          echo "Installed packages:"
          .venv/bin/pip list

      - name: Pull data via DVC
        run: |
          echo "Running dvc pull --force"
          .venv/bin/dvc pull --force

      - name: Run pytest suite
        run: |
          echo "Running pytest for predict service"
          .venv/bin/pytest plugins/cd4ml/tests/test_predict_service.py -v -rA

      - name: Push artifacts via DVC
        run: |
          echo "Running dvc push"
          .venv/bin/dvc push

  # 2) Rebuild only those Docker services whose code changed
  rebuild-images:
    name: Build changed Docker service images
    needs: test-venv
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine changed services
        id: services
        run: |
          CHANGED=$(git diff --name-only ${{ github.sha }} ${{ github.sha }}^ \
            | cut -d/ -f1 \
            | sort -u \
            | grep -E '^(dockerfiles|plugins|dvc-sync|preprocessing|model_training|model_validation|tests|auth_service|predict_service)$' \
            || echo "")
          SERVICES=""
          for D in $CHANGED; do
            case "$D" in
              dockerfiles/dvc)             SERVICES="$SERVICES dvc-sync";;
              dockerfiles/preprocessing)    SERVICES="$SERVICES preprocessing";;
              dockerfiles/model_training)   SERVICES="$SERVICES model_training";;
              dockerfiles/model_validation) SERVICES="$SERVICES model_validation";;
              dockerfiles/tests)            SERVICES="$SERVICES tests";;
              dockerfiles/auth_service)     SERVICES="$SERVICES auth_service";;
              dockerfiles/predict_service)  SERVICES="$SERVICES predict_service";;
            esac
          done
          if [ -z "$SERVICES" ]; then
            echo "No service-specific changes detected; building all."
            echo "::set-output name=list::"
          else
            echo "Building these services:$SERVICES"
            echo "::set-output name=list::$SERVICES"
          fi

      - name: Build changed images
        run: |
          if [ -z "${{ steps.services.outputs.list }}" ]; then
            docker compose build
          else
            docker compose build ${{ steps.services.outputs.list }}
          fi

  # 3) Push rebuilt images to DockerHub
  push-image:
    name: Push images to DockerHub (dev & SHA tags)
    needs: rebuild-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push images
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:dev
            ${{ env.IMAGE_NAME }}:${{ env.TAG }}
