# .github/workflows/docker-publish.yml
name: Build, Test & Push Docker Images

on:
  push:
    branches:
      - main
      - develop
      - dev_new-feature-githubactions

permissions:
  contents: read

jobs:
  build-test-push:
    # Damit pro Service+Branch nur ein Run gleichzeitig läuft
    concurrency:
      group: build-${{ matrix.service }}-${{ github.ref_name }}
      cancel-in-progress: true

    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth_service, predict_service]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build ${{ matrix.service }}
        run: |
          docker build \
            -f dockerfiles/${{ matrix.service }}/Dockerfile \
            -t igurstein/rakuten_dev:${{ matrix.service }}-${{ github.ref_name }} \
            .

      - name: Run unit tests for ${{ matrix.service }}
        run: |
          docker run --rm igurstein/rakuten_dev:${{ matrix.service }}-${{ github.ref_name }} \
            sh -c "pytest plugins/cd4ml/tests/${{ matrix.service }} -v -rA"

      - name: Push ${{ matrix.service }} to Docker Hub
        run: |
          docker push igurstein/rakuten_dev:${{ matrix.service }}-${{ github.ref_name }}

      - name: Tag ${{ matrix.service }} as latest
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag \
            igurstein/rakuten_dev:${{ matrix.service }}-main \
            igurstein/rakuten_dev:${{ matrix.service }}-latest
          docker push igurstein/rakuten_dev:${{ matrix.service }}-latest
